# Project Data Analysis & Visualization Menggunakan Global Weather Dataset

## Columns descriptions:

- country: Country of the weather data
- location_name: Name of the location (city)
- latitude: Latitude coordinate of the location
- longitude: Longitude coordinate of the location
- timezone: Timezone of the location
- last_updated_epoch: Unix timestamp of the last data update
- last_updated: Local time of the last data update
- temperature_celsius: Temperature in degrees Celsius
- temperature_fahrenheit: Temperature in degrees Fahrenheit
- condition_text: Weather condition description
- wind_mph: Wind speed in miles per hour
- wind_kph: Wind speed in kilometers per hour
- wind_degree: Wind direction in degrees
- wind_direction: Wind direction as a 16-point compass
- pressure_mb: Pressure in millibars
- pressure_in: Pressure in inches
- precip_mm: Precipitation amount in millimeters
- precip_in: Precipitation amount in inches
- humidity: Humidity as a percentage
- cloud: Cloud cover as a percentage
- feels_like_celsius: Feels-like temperature in Celsius
- feels_like_fahrenheit: Feels-like temperature in Fahrenheit
- visibility_km: Visibility in kilometers
- visibility_miles: Visibility in miles
- uv_index: UV Index
- gust_mph: Wind gust in miles per hour
- gust_kph: Wind gust in kilometers per hour
- air_quality_Carbon_Monoxide: Air quality measurement: Carbon Monoxide
- air_quality_Ozone: Air quality measurement: Ozone
- air_quality_Nitrogen_dioxide: Air quality measurement: Nitrogen Dioxide
- air_quality_Sulphur_dioxide: Air quality measurement: Sulphur Dioxide
- air_quality_PM2.5: Air quality measurement: PM2.5
- air_quality_PM10: Air quality measurement: PM10
- air_quality_us-epa-index: Air quality measurement: US EPA Index
- air_quality_gb-defra-index: Air quality measurement: GB DEFRA Index
- sunrise: Local time of sunrise
- sunset: Local time of sunset
- moonrise: Local time of moonrise
- moonset: Local time of moonset
- moon_phase: Current moon phase
- moon_illumination: Moon illumination percentage

In [323]:
import pandas as pd
import numpy as np
import pycountry_convert as pc
from sklearn.ensemble import IsolationForest
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt

In [502]:
df = pd.read_csv("Global_Weather.csv")
df.shape

df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

## Cek kolom dan tipe data

In [325]:
# Melihat nama kolom
df.columns.tolist()

# melihat tipe data per kolom
df.dtypes

# Cek missing values per kolom
df.isnull().sum()

# Cek persentase missing
(df.isnull().sum() / len(df) * 100).round(2).sort_values(ascending=False)

# check ulang head dataset
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

### Check duplikasi, shape dataset, contoh data dan statistik angka

In [326]:
df.duplicated().sum()

np.int64(0)

In [327]:
df.shape

(72680, 41)

In [328]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

### Validasi

In [329]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,72680.000000,72680.000000,7.268000e+04,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000,...,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000,72680.000000
mean,19.131726,22.192388,1.732041e+09,22.178485,71.922887,8.278520,13.326626,168.654554,1014.064241,29.944688,...,18.891186,524.755661,63.959137,15.354301,11.389241,26.072034,54.066043,1.752422,2.764062,50.335856
std,24.473876,65.817916,9.365241e+06,9.389486,16.900842,8.651946,13.921876,103.626180,12.561074,0.370895,...,15.849198,896.920503,34.672720,26.142281,45.230503,43.078374,166.945878,0.994329,2.610547,34.972720
min,-41.300000,-175.200000,1.715849e+09,-24.900000,-12.800000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.723982e+09,16.800000,62.200000,4.000000,6.500000,80.000000,1010.000000,29.830000,...,10.700000,233.100000,41.000000,1.110000,0.800000,6.400000,9.620000,1.000000,1.000000,16.000000
50%,17.250000,23.316700,1.732092e+09,24.500000,76.100000,6.900000,11.200000,160.000000,1013.000000,29.920000,...,16.200000,329.300000,61.000000,3.885000,2.405000,14.430000,21.645000,1.000000,2.000000,51.000000
75%,40.400000,50.580000,1.740132e+09,28.300000,82.900000,11.400000,18.400000,256.000000,1017.000000,30.040000,...,25.100000,510.600000,82.000000,17.020000,9.100000,30.525000,46.805000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.748162e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

### tidak ada missing value namun ada kejanggalan data yaitu wind_mph terlalu tinggi, gust_kph, pressure_mb, air quality carbon nya -, air quality -, dan temperatur suhu.

In [330]:
df = df.replace(-9999, np.nan)

In [331]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     1
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     1
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [332]:
# Melihat nama kolom
df.columns.tolist()

# melihat tipe data per kolom
df.dtypes

# Cek missing values per kolom
df.isnull().sum()

# Cek persentase missing
(df.isnull().sum() / len(df) * 100).round(2).sort_values(ascending=False)

country                         0.0
location_name                   0.0
latitude                        0.0
longitude                       0.0
timezone                        0.0
last_updated_epoch              0.0
last_updated                    0.0
temperature_celsius             0.0
temperature_fahrenheit          0.0
condition_text                  0.0
wind_mph                        0.0
wind_kph                        0.0
wind_degree                     0.0
wind_direction                  0.0
pressure_mb                     0.0
pressure_in                     0.0
precip_mm                       0.0
precip_in                       0.0
humidity                        0.0
cloud                           0.0
feels_like_celsius              0.0
feels_like_fahrenheit           0.0
visibility_km                   0.0
visibility_miles                0.0
uv_index                        0.0
gust_mph                        0.0
gust_kph                        0.0
air_quality_Carbon_Monoxide     0.0
air_quality_Ozone               0.0
air_quality_Nitrogen_dioxide    0.0
air_quality_Sulphur_dioxide     0.0
air_quality_PM2.5               0.0
air_quality_PM10                0.0
air_quality_us-epa-index        0.0
air_quality_gb-defra-index      0.0
sunrise                         0.0
sunset                          0.0
moonrise                        0.0
moonset                         0.0
moon_phase                      0.0
moon_illumination               0.0
dtype: float64

In [333]:
df["wind_kph"].sort_values(ascending=False).head(10)

df = df[df["wind_kph"] < 200]

In [334]:
Q1 = df["wind_kph"].quantile(0.25)
Q3 = df["wind_kph"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(lower)
print(upper)

-11.349999999999998
36.25

### Hapus data yang outlier

In [335]:
df = df[df["wind_kph"] < 150]

In [336]:
df = df.replace(-9999, np.nan)

In [337]:
df = df[df["wind_kph"] < 150]

In [338]:
df = df[df["air_quality_PM10"] >= 0] ## angka polusi tidak mungkin negatif

In [339]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,72674.000000,72674.000000,7.267400e+04,72674.000000,72674.000000,72674.000000,72674.000000,72674.000000,72674.000000,72674.000000,...,72674.000000,72673.000000,72674.000000,72674.000000,72673.000000,72674.000000,72674.000000,72674.000000,72674.000000,72674.000000
mean,19.132946,22.190644,1.732042e+09,22.178362,71.922664,8.245912,13.274148,168.660993,1014.063943,29.944679,...,18.838627,524.921326,63.960747,15.355189,11.527497,26.064943,54.094034,1.752401,2.764070,50.333888
std,24.474173,65.817226,9.364845e+06,9.389652,16.901143,5.255935,8.454821,103.626179,12.561428,0.370906,...,11.344434,896.110382,34.673076,26.143062,25.827457,43.019746,166.803070,0.994230,2.610482,34.972397
min,-41.300000,-175.200000,1.715849e+09,-24.900000,-12.800000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,81.000000,0.000000,0.000000,0.000000,0.168000,0.168000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.723982e+09,16.800000,62.200000,4.000000,6.500000,80.000000,1010.000000,29.830000,...,10.700000,233.100000,41.000000,1.110000,0.800000,6.400000,9.620000,1.000000,1.000000,16.000000
50%,17.250000,23.316700,1.732092e+09,24.500000,76.100000,6.900000,11.200000,160.000000,1013.000000,29.920000,...,16.200000,329.300000,61.000000,3.885000,2.405000,14.430000,21.645000,1.000000,2.000000,51.000000
75%,40.400000,50.580000,1.740132e+09,28.300000,82.900000,11.400000,18.400000,256.000000,1017.000000,30.040000,...,25.100000,510.600000,82.000000,17.020000,9.100000,30.525000,46.805000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.748162e+09,49.200000,120.600000,56.600000,91.100000,360.000000,3006.000000,88.770000,...,119.900000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

### Mengisi nilai kosong , sebelumnya ada di carbon monoxide dan sekarang diisi dengan nilai median saja

In [340]:
df = df.fillna(df.median(numeric_only=True))

In [341]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

### Penentuan Classification hanya memerlukan X saja tidak perlu Y nya untuk anomaly detection dan clustering karena tidak perlu menebak namun mencari pola yang aneh yang ada di data : unsupervised learning, no target, real anomaly detection, geographic intelligence, dan climate analysis

In [342]:
X = df[
    [
        "temperature_celsius",
        "humidity",
        "wind_kph",
        "pressure_mb",
        "uv_index",
        "air_quality_PM2.5",
        "air_quality_PM10"
    ]
]

In [343]:
y = df["condition_text"]

In [344]:
y = df["temperature_celsius"]  # celcius

In [345]:
y = df["humidity"] # humidity

### Grouping data = benua

df["continent"]

In [412]:
def get_continent(country_name):

    try:

        country_code = pc.country_name_to_country_alpha2(
            country_name
        )

        continent_code = pc.country_alpha2_to_continent_code(
            country_code
        )

        continent_names = {
            "AF": "Africa",
            "AS": "Asia",
            "EU": "Europe",
            "NA": "North America",
            "SA": "South America",
            "OC": "Oceania"
        }

        return continent_names.get(continent_code)

    except:

        return "Unknown"
    


# ====================================
# CREATE CONTINENT FUNCTION
# ====================================

def get_continent(country_name):

    try:

        country_code = (
            pc.country_name_to_country_alpha2(
                country_name
            )
        )

        continent_code = (
            pc.country_alpha2_to_continent_code(
                country_code
            )
        )

        continent_map = {

            "AF": "Africa",
            "AS": "Asia",
            "EU": "Europe",
            "NA": "North America",
            "SA": "South America",
            "OC": "Oceania"
        }

        return continent_map.get(
            continent_code,
            "Unknown"
        )

    except:
        return "Unknown"

# ====================================
# CREATE CONTINENT COLUMN
# ====================================

df_clean["continent"] = (
    df_clean["country"]
    .apply(get_continent)
)

print("\n✅ Continent column created!")

print("\n🌍 Continent distribution:")
print(df_clean["continent"].value_counts())


# ====================================
# CHECK
# ====================================

print(df_clean["continent"].value_counts())

print("\nColumns:")
print(df_clean.columns.tolist())





# ====================================
# CHECK UNKNOWN COUNTRIES
# ====================================

unknown_countries = (
    df_clean[
        df_clean["continent"] == "Unknown"
    ]["country"]
    .unique()
)

print("\n⚠️ Unknown countries:")
print(sorted(unknown_countries))

# ====================================
# KEEP IMPORTANT COLUMNS ONLY
# ====================================

selected_columns = [

    # location
    "country",
    "location_name",
    "latitude",
    "longitude",
    "continent",

    # weather
    "temperature_celsius",
    "humidity",
    "wind_kph",
    "pressure_mb",
    "uv_index",
    "cloud",
    "visibility_km",

    # air quality
    "air_quality_PM2.5",
    "air_quality_PM10",
    "air_quality_Ozone",
    "air_quality_Carbon_Monoxide",

    # weather label
    "condition_text"
]

df_clean = df_clean[selected_columns]

print("\n✅ Final selected columns:")
print(df_clean.columns.tolist())

# ====================================
# REMOVE DUPLICATES
# ====================================

before_duplicates = df_clean.shape[0]

df_clean = df_clean.drop_duplicates()

after_duplicates = df_clean.shape[0]

print("\n🧹 Duplicates removed:")
print(before_duplicates - after_duplicates)

# ====================================
# CHECK MISSING VALUES
# ====================================

print("\n🔍 Missing values BEFORE cleaning:")
print(df_clean.isnull().sum())

# remove missing values
df_clean = df_clean.dropna()

print("\n✅ Missing values AFTER cleaning:")
print(df_clean.isnull().sum())

# ====================================
# REMOVE INVALID VALUES
# ====================================

# remove invalid air quality
df_clean = df_clean[

    (df_clean["air_quality_PM2.5"] >= 0) &

    (df_clean["air_quality_PM10"] >= 0) &

    (
        df_clean[
            "air_quality_Carbon_Monoxide"
        ] >= 0
    )
]

# remove unrealistic wind
df_clean = (
    df_clean[
        df_clean["wind_kph"] < 200
    ]
)

print("\n✅ Invalid values removed!")
print("Dataset shape:")
print(df_clean.shape)

# ====================================
# RESET INDEX
# ====================================

df_clean = (
    df_clean
    .reset_index(drop=True)
)

# ====================================
# FEATURES FOR ANOMALY DETECTION
# ====================================

X = df_clean[

    [
        "temperature_celsius",
        "humidity",
        "wind_kph",
        "pressure_mb",
        "uv_index",
        "cloud",
        "visibility_km",
        "air_quality_PM2.5",
        "air_quality_PM10"
    ]
]

print("\n Features for anomaly detection:")
print(X.head())

# ====================================
# ANOMALY DETECTION
# ====================================

model = IsolationForest(

    contamination=0.02,
    random_state=42
)

# train model
model.fit(X)

# predict anomaly
predictions = model.predict(X)

# save prediction
df_clean["anomaly"] = predictions

print("\n🚨 Anomaly results:")
print(df_clean["anomaly"].value_counts())

# ====================================
# CONTINENT VS ANOMALY
# ====================================

print("\n🌍 Continent vs Anomaly:")
print(

    df_clean
    .groupby(
        ["continent", "anomaly"]
    )
    .size()
)


from sklearn.ensemble import IsolationForest

# ====================================
# FEATURES
# ====================================

X = df_clean[

    [
        "temperature_celsius",
        "humidity",
        "wind_kph",
        "pressure_mb",
        "uv_index",
        "cloud",
        "visibility_km",
        "air_quality_PM2.5",
        "air_quality_PM10"
    ]
]

# ====================================
# MODEL
# ====================================

model = IsolationForest(
    contamination=0.02,
    random_state=42
)

# train model
model.fit(X)

# create predictions
predictions = model.predict(X)

# save anomaly column
df_clean["anomaly"] = predictions

✅ Continent column created!

🌍 Continent distribution:
continent
Africa           18290
Asia             18238
Europe           16456
North America     8508
Oceania           4477
South America     4451
Unknown           2260
Name: count, dtype: int64
continent
Africa           18290
Asia             18238
Europe           16456
North America     8508
Oceania           4477
South America     4451
Unknown           2260
Name: count, dtype: int64

Columns:
['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'anomaly', 'continent']

⚠️ Unknown countries:
['Bélgica', 'Democratic Republic of Congo', 'Estonie', 'Fiji Islands', 'Inde', 'Jemen', 'Komoren', 'Kosovo', 'Kyrghyzstan', 'Letonia', 'Malásia', 'Marrocos', 'Mexique', 'Polônia', 'Saint-Vincent-et-les-Grenadines', 'Saudi Arabien', 'Seychelles Islands', 'Südkorea', 'Timor-Leste', 'Turkménistan', 'USA United States of America', 'Vatican City', 'Гватемала', 'Польша', 'Турция', 'كولومبيا', '火鸡']

✅ Final selected columns:
['country', 'location_name', 'latitude', 'longitude', 'continent', 'temperature_celsius', 'humidity', 'wind_kph', 'pressure_mb', 'uv_index', 'cloud', 'visibility_km', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_Ozone', 'air_quality_Carbon_Monoxide', 'condition_text']

🧹 Duplicates removed:
0

🔍 Missing values BEFORE cleaning:
country                        0
location_name                  0
latitude                       0
longitude                      0
continent                      0
temperature_celsius            0
humidity                       0
wind_kph                       0
pressure_mb                    0
uv_index                       0
cloud                          0
visibility_km                  0
air_quality_PM2.5              0
air_quality_PM10               0
air_quality_Ozone              0
air_quality_Carbon_Monoxide    0
condition_text                 0
dtype: int64

✅ Missing values AFTER cleaning:
country                        0
location_name                  0
latitude                       0
longitude                      0
continent                      0
temperature_celsius            0
humidity                       0
wind_kph                       0
pressure_mb                    0
uv_index                       0
cloud                          0
visibility_km                  0
air_quality_PM2.5              0
air_quality_PM10               0
air_quality_Ozone              0
air_quality_Carbon_Monoxide    0
condition_text                 0
dtype: int64

✅ Invalid values removed!
Dataset shape:
(72674, 17)

 Features for anomaly detection:
   temperature_celsius  humidity  wind_kph  pressure_mb  uv_index  cloud  \
0                 26.6        24      13.3       1012.0       7.0     30
1                 19.0        94      11.2       1012.0       5.0     75
2                 23.0        29      15.1       1011.0       5.0      0
3                  6.3        61      11.9       1007.0       2.0    100
4                 26.0        89      13.0       1011.0       8.0     50

   visibility_km  air_quality_PM2.5  air_quality_PM10
0           10.0                8.4              26.6
1           10.0                1.1               2.0
2           10.0               10.4              18.4
3            2.0                0.7               0.9
4           10.0              183.4             262.3

🚨 Anomaly results:
anomaly
 1    71220
-1     1454
Name: count, dtype: int64

🌍 Continent vs Anomaly:
continent      anomaly
Africa         -1           277
                1         18010
Asia           -1           710
                1         17527
Europe         -1           137
                1         16319
North America  -1            87
                1          8419
Oceania        -1           111
                1          4366
South America  -1           129
                1          4322
Unknown        -1             3
                1          2257
dtype: int64

In [413]:
df["continent"] = df["country"].apply(get_continent)

In [414]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination',
       'continent'],
      dtype='str')

### Data untuk rata-rata suhu per benua dan rata tertinggi polusi per benua

In [415]:
df.groupby("continent")["temperature_celsius"].mean()

continent
Africa           26.817638
Asia             24.265747
Europe           14.602534
North America    22.516855
Oceania          24.428144
South America    18.726174
Unknown          24.022699
Name: temperature_celsius, dtype: float64

In [416]:
df.groupby("continent")["air_quality_PM2.5"].mean()

continent
Africa           26.406530
Asia             43.251681
Europe           18.042564
North America    13.833658
Oceania           7.241723
South America    32.295557
Unknown          14.310586
Name: air_quality_PM2.5, dtype: float64

## Isolation forest untuk mencari data yang aneh

In [417]:
from sklearn.ensemble import IsolationForest

In [418]:
X.head()

,temperature_celsius,humidity,wind_kph,pressure_mb,uv_index,cloud,visibility_km,air_quality_PM2.5,air_quality_PM10
0,26.6,24,13.3,1012.0,7.0,30,10.0,8.4,26.6
1,19.0,94,11.2,1012.0,5.0,75,10.0,1.1,2.0
2,23.0,29,15.1,1011.0,5.0,0,10.0,10.4,18.4
3,6.3,61,11.9,1007.0,2.0,100,2.0,0.7,0.9
4,26.0,89,13.0,1011.0,8.0,50,10.0,183.4,262.3

In [419]:
X.shape

(72674, 9)

In [420]:
X.isnull().sum()

temperature_celsius    0
humidity               0
wind_kph               0
pressure_mb            0
uv_index               0
cloud                  0
visibility_km          0
air_quality_PM2.5      0
air_quality_PM10       0
dtype: int64

In [421]:
from sklearn.ensemble import IsolationForest

In [422]:
X = df[
    [
        "temperature_celsius",
        "humidity",
        "wind_kph",
        "pressure_mb",
        "uv_index",
        "air_quality_PM2.5",
        "air_quality_PM10"
    ]
]

In [423]:
model = IsolationForest(
    contamination=0.02,
    random_state=42
)

In [424]:
model.fit(X)

IsolationForest(contamination=0.02, random_state=42)

In [425]:
predictions = model.predict(X)

In [426]:
predictions[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [427]:
df["anomaly"] = predictions

In [428]:
df[df["anomaly"] == -1]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,anomaly
35,Chile,Santiago,-33.4500,-70.6700,America/Santiago,1715849100,2024-05-16 04:45,1.0,33.8,Clear,...,5,10,07:28 AM,05:50 PM,02:23 PM,12:56 AM,Waxing Gibbous,55,South America,-1
230,Chile,Santiago,-33.4500,-70.6700,America/Santiago,1715868000,2024-05-16 10:00,2.0,35.6,Sunny,...,6,10,07:28 AM,05:50 PM,02:23 PM,12:56 AM,Waxing Gibbous,55,South America,-1
231,China,Beijing,39.9300,116.3900,Asia/Shanghai,1715868000,2024-05-16 22:00,23.0,73.4,Clear,...,5,10,04:58 AM,07:24 PM,12:17 PM,01:39 AM,Waxing Gibbous,55,Asia,-1
273,Indonesia,Jakarta,-6.2100,106.8500,Asia/Jakarta,1715868000,2024-05-16 21:00,29.0,84.2,Mist,...,6,10,05:54 AM,05:44 PM,12:50 PM,12:15 AM,Waxing Gibbous,55,Asia,-1
425,Chile,Santiago,-33.4500,-70.6700,America/Santiago,1715961600,2024-05-17 12:00,9.0,48.2,Partly cloudy,...,5,10,07:29 AM,05:49 PM,02:47 PM,01:52 AM,Waxing Gibbous,64,South America,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72563,Indonesia,Jakarta,-6.2146,106.8451,Asia/Jakarta,1748161800,2025-05-25 15:30,28.1,82.6,Light rain shower,...,5,10,05:56 AM,05:44 PM,03:44 AM,03:55 PM,Waning Crescent,9,Asia,-1
72575,Kuwait,Kuwait City,29.3667,47.9600,Asia/Kuwait,1748161800,2025-05-25 11:30,41.8,107.2,Mist,...,4,10,04:51 AM,06:39 PM,03:03 AM,04:55 PM,Waning Crescent,8,Asia,-1
72616,Pakistan,Islamabad,33.7000,73.1667,Asia/Karachi,1748161800,2025-05-25 13:30,37.7,99.8,Sunny,...,4,10,05:01 AM,07:08 PM,03:13 AM,05:18 PM,Waning Crescent,8,Asia,-1
72626,Qatar,Doha,25.2867,51.5333,Asia/Qatar,1748161800,2025-05-25 11:30,44.0,111.2,Sunny,...,4,10,04:45 AM,06:17 PM,02:55 AM,04:33 PM,Waning Crescent,8,Asia,-1
72636,Saudi Arabia,Riyadh,24.6408,46.7728,Asia/Riyadh,1748161800,2025-05-25 11:30,40.1,104.2,Sunny,...,6,10,05:05 AM,06:34 PM,03:15 AM,04:52 PM,Waning Crescent,8,Asia,-1

In [429]:
df.groupby("continent")["anomaly"].value_counts()

continent      anomaly
Africa          1         17827
               -1           463
Asia            1         17427
               -1           811
Europe          1         16397
               -1            59
North America   1          8505
               -1             3
Oceania         1          4477
South America   1          4334
               -1           117
Unknown         1          2259
               -1             1
Name: count, dtype: int64

In [430]:
df.to_csv("Global_Weather_Clean.csv", index=False)

In [431]:
df = pd.read_csv("Global_Weather_Clean.csv")

In [432]:
import pandas as pd

df = pd.read_csv("Global_Weather.csv")

df_clean = df.copy()

import pycountry_convert as pc
import pycountry


from sklearn.ensemble import IsolationForest

# ====================================
# LOAD DATASET
# ====================================

df = pd.read_csv("Global_Weather.csv")

print("Dataset berhasil dibuka!")
print(df.shape)

# ====================================
# ADD CONTINENT COLUMN
# ====================================

continent_map = {

    # ASIA
    "Indonesia": "Asia",
    "Japan": "Asia",
    "China": "Asia",
    "India": "Asia",
    "South Korea": "Asia",
    "Thailand": "Asia",
    "Malaysia": "Asia",
    "Singapore": "Asia",
    "Pakistan": "Asia",
    "Afghanistan": "Asia",

    # EUROPE
    "France": "Europe",
    "Germany": "Europe",
    "Italy": "Europe",
    "Spain": "Europe",
    "United Kingdom": "Europe",
    "Netherlands": "Europe",
    "Belgium": "Europe",
    "Switzerland": "Europe",

    # AFRICA
    "Nigeria": "Africa",
    "Egypt": "Africa",
    "South Africa": "Africa",
    "Kenya": "Africa",
    "Morocco": "Africa",

    # NORTH AMERICA
    "United States of America": "North America",
    "Canada": "North America",
    "Mexico": "North America",

    # SOUTH AMERICA
    "Brazil": "South America",
    "Argentina": "South America",
    "Chile": "South America",
    "Colombia": "South America",

    # OCEANIA
    "Australia": "Oceania",
    "New Zealand": "Oceania"
}

df["continent"] = df["country"].map(continent_map)

# unknown continent
df["continent"] = df["continent"].fillna("Unknown")

print("\nContinent column berhasil dibuat!")
print(df["continent"].value_counts())

# ====================================
# KEEP IMPORTANT COLUMNS ONLY
# ====================================

selected_columns = [

    "country",
    "location_name",
    "latitude",
    "longitude",
    "continent",

    "temperature_celsius",
    "humidity",
    "wind_kph",
    "pressure_mb",
    "uv_index",
    "cloud",
    "visibility_km",

    "air_quality_PM2.5",
    "air_quality_PM10",
    "air_quality_Ozone",
    "air_quality_Carbon_Monoxide",

    "condition_text"
]

df = df[selected_columns]

print("\nKolom final:")
print(df.columns.tolist())

# ====================================
# REMOVE DUPLICATES
# ====================================

before_duplicates = df.shape[0]

df = df.drop_duplicates()

after_duplicates = df.shape[0]

print("\nDuplicates removed:")
print(before_duplicates - after_duplicates)

# ====================================
# REMOVE MISSING VALUES
# ====================================

print("\nMissing values sebelum cleaning:")
print(df.isnull().sum())

df = df.dropna()

print("\nMissing values setelah cleaning:")
print(df.isnull().sum())

# ====================================
# REMOVE INVALID VALUES
# ====================================

# remove invalid air quality
df = df[
    (df["air_quality_PM2.5"] >= 0) &
    (df["air_quality_PM10"] >= 0) &
    (df["air_quality_Carbon_Monoxide"] >= 0)
]

# remove unrealistic wind
df = df[df["wind_kph"] < 200]

print("\nDataset setelah remove invalid values:")
print(df.shape)

# ====================================
# RESET INDEX
# ====================================

df = df.reset_index(drop=True)

# ====================================
# FINAL FEATURES FOR ANOMALY
# ====================================

X = df[
    [
        "temperature_celsius",
        "humidity",
        "wind_kph",
        "pressure_mb",
        "uv_index",
        "cloud",
        "visibility_km",
        "air_quality_PM2.5",
        "air_quality_PM10"
    ]
]

print("\nX features:")
print(X.head())

# ====================================
# ANOMALY DETECTION
# ====================================

model = IsolationForest(
    contamination=0.02,
    random_state=42
)

model.fit(X)

predictions = model.predict(X)

df["anomaly"] = predictions

print("\nAnomaly results:")
print(df["anomaly"].value_counts())

# ====================================
# CONTINENT + ANOMALY ANALYSIS
# ====================================

print("\nContinent vs Anomaly:")
print(
    df.groupby(
        ["continent", "anomaly"]
    ).size()
)

# ====================================
# CHECK FINAL DATASET
# ====================================

print("\nFinal dataset shape:")
print(df.shape)

print("\nFinal columns:")
print(df.columns.tolist())

print("\nDuplicate check:")
print(df.duplicated().sum())

print("\nMissing check:")
print(df.isnull().sum())

print("\nDescribe dataset:")
print(df.describe())

print("\nSample anomalies:")
print(
    df[df["anomaly"] == -1]
    .head()
)

# ====================================
# SAVE CLEAN DATASET
# ====================================

df.to_csv(
    "Global_Weather_Clean.csv",
    index=False
)

print("\nGlobal_Weather_Clean.csv berhasil disimpan!")

Dataset berhasil dibuka!
(72680, 41)

Continent column berhasil dibuat!
continent
Unknown          60005
Asia              4481
Europe            3356
Africa            1868
South America     1114
North America     1108
Oceania            748
Name: count, dtype: int64

Kolom final:
['country', 'location_name', 'latitude', 'longitude', 'continent', 'temperature_celsius', 'humidity', 'wind_kph', 'pressure_mb', 'uv_index', 'cloud', 'visibility_km', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_Ozone', 'air_quality_Carbon_Monoxide', 'condition_text']

Duplicates removed:
0

Missing values sebelum cleaning:
country                        0
location_name                  0
latitude                       0
longitude                      0
continent                      0
temperature_celsius            0
humidity                       0
wind_kph                       0
pressure_mb                    0
uv_index                       0
cloud                          0
visibility_km                  0
air_quality_PM2.5              0
air_quality_PM10               0
air_quality_Ozone              0
air_quality_Carbon_Monoxide    0
condition_text                 0
dtype: int64

Missing values setelah cleaning:
country                        0
location_name                  0
latitude                       0
longitude                      0
continent                      0
temperature_celsius            0
humidity                       0
wind_kph                       0
pressure_mb                    0
uv_index                       0
cloud                          0
visibility_km                  0
air_quality_PM2.5              0
air_quality_PM10               0
air_quality_Ozone              0
air_quality_Carbon_Monoxide    0
condition_text                 0
dtype: int64

Dataset setelah remove invalid values:
(72674, 17)

X features:
   temperature_celsius  humidity  wind_kph  pressure_mb  uv_index  cloud  \
0                 26.6        24      13.3       1012.0       7.0     30
1                 19.0        94      11.2       1012.0       5.0     75
2                 23.0        29      15.1       1011.0       5.0      0
3                  6.3        61      11.9       1007.0       2.0    100
4                 26.0        89      13.0       1011.0       8.0     50

   visibility_km  air_quality_PM2.5  air_quality_PM10
0           10.0                8.4              26.6
1           10.0                1.1               2.0
2           10.0               10.4              18.4
3            2.0                0.7               0.9
4           10.0              183.4             262.3

Anomaly results:
anomaly
 1    71220
-1     1454
Name: count, dtype: int64

Continent vs Anomaly:
continent      anomaly
Africa         -1            19
                1          1849
Asia           -1           308
                1          4173
Europe         -1            28
                1          3328
North America  -1            74
                1          1034
Oceania        -1             4
                1           744
South America  -1           125
                1           989
Unknown        -1           896
                1         59103
dtype: int64

Final dataset shape:
(72674, 18)

Final columns:
['country', 'location_name', 'latitude', 'longitude', 'continent', 'temperature_celsius', 'humidity', 'wind_kph', 'pressure_mb', 'uv_index', 'cloud', 'visibility_km', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_Ozone', 'air_quality_Carbon_Monoxide', 'condition_text', 'anomaly']

Duplicate check:
0

Missing check:
country                        0
location_name                  0
latitude                       0
longitude                      0
continent                      0
temperature_celsius            0
humidity                       0
wind_kph                       0
pressure_mb                    0
uv_index                       0
cloud                          0
visibility_km                  0
air_quality_PM2.5              0
air_quality_PM10               0
air_quality_Ozone              0
air_quality_Carbon_Monoxide    0
condition_text                 0
anomaly                        0
dtype: int64

Describe dataset:
           latitude     longitude  temperature_celsius      humidity  \
count  72674.000000  72674.000000         72674.000000  72674.000000
mean      19.132461     22.193950            22.178303     63.638192
std       24.474562     65.819039             9.389615     24.318317
min      -41.300000   -175.200000           -24.900000      2.000000
25%        3.750000     -6.836100            16.800000     46.000000
50%       17.250000     23.316700            24.500000     69.000000
75%       40.400000     50.580000            28.300000     83.000000
max       64.150000    179.220000            49.200000    100.000000

           wind_kph   pressure_mb      uv_index         cloud  visibility_km  \
count  72674.000000  72674.000000  72674.000000  72674.000000   72674.000000
mean      13.276283   1014.063861      3.983365     39.891268       9.614332
std        8.475312     12.561428      3.627722     33.855698       2.532557
min        3.600000    947.000000      0.000000      0.000000       0.000000
25%        6.500000   1010.000000      0.700000      2.000000      10.000000
50%       11.200000   1013.000000      3.300000     31.000000      10.000000
75%       18.400000   1017.000000      7.000000     75.000000      10.000000
max      172.100000   3006.000000     16.300000    100.000000      32.000000

       air_quality_PM2.5  air_quality_PM10  air_quality_Ozone  \
count       72674.000000      72674.000000       72674.000000
mean           26.064957         54.093943          63.960342
std            43.019738        166.803095          34.673615
min             0.168000          0.168000           0.000000
25%             6.400000          9.620000          41.000000
50%            14.430000         21.645000          61.000000
75%            30.525000         46.805000          82.000000
max          1614.100000       6037.290000         480.700000

       air_quality_Carbon_Monoxide       anomaly
count                 72674.000000  72674.000000
mean                    524.916262      0.959986
std                     896.105257      0.280051
min                      81.000000     -1.000000
25%                     233.100000      1.000000
50%                     329.300000      1.000000
75%                     510.600000      1.000000
max                   38879.398000      1.000000

Sample anomalies:
       country   location_name  latitude  longitude      continent  \
35       Chile        Santiago    -33.45     -70.67  South America
68   Guatemala  Guatemala City     14.62     -90.53        Unknown
78   Indonesia         Jakarta     -6.21     106.85           Asia
230      Chile        Santiago    -33.45     -70.67  South America
273  Indonesia         Jakarta     -6.21     106.85           Asia

     temperature_celsius  humidity  wind_kph  pressure_mb  uv_index  cloud  \
35                   1.0        93       6.8       1019.0       1.0      0
68                  20.0        88      22.0       1019.0       1.0    100
78                  32.0        63      24.1       1007.0       8.0     50
230                  2.0        87       6.8       1020.0       4.0      0
273                 29.0        84      15.1       1010.0       1.0     75

     visibility_km  air_quality_PM2.5  air_quality_PM10  air_quality_Ozone  \
35             7.0              211.1             268.6                0.0
68             5.0              132.0             178.1                0.4
78             8.0              196.1             224.0              303.3
230            6.0              714.1             873.4               19.7
273            5.0              492.5             621.5                0.0

     air_quality_Carbon_Monoxide condition_text  anomaly
35                      2723.700          Clear       -1
68                      2243.000           Mist       -1
78                      3471.400  Partly cloudy       -1
230                     9719.900          Sunny       -1
273                    19653.301           Mist       -1

Global_Weather_Clean.csv berhasil disimpan!

# Raw messy weather dataset : Country to continent

In [433]:
df[df["continent"] == "Unknown"]["country"].unique()

<ArrowStringArray>
[                        'Albania',                         'Algeria',
                         'Andorra',                          'Angola',
             'Antigua and Barbuda',                         'Armenia',
                         'Austria',                      'Azerbaijan',
                         'Bahamas',                         'Bahrain',
 ...
                         'Polônia',                        'Marrocos',
                          'Турция', 'Saint-Vincent-et-les-Grenadines',
                   'Saudi Arabien',                        'Südkorea',
                         'Bélgica',                    'Turkménistan',
                              '火鸡',                           'Jemen']
Length: 178, dtype: str

In [434]:
df[df["continent"] == "Unknown"]["country"].unique()

<ArrowStringArray>
[                        'Albania',                         'Algeria',
                         'Andorra',                          'Angola',
             'Antigua and Barbuda',                         'Armenia',
                         'Austria',                      'Azerbaijan',
                         'Bahamas',                         'Bahrain',
 ...
                         'Polônia',                        'Marrocos',
                          'Турция', 'Saint-Vincent-et-les-Grenadines',
                   'Saudi Arabien',                        'Südkorea',
                         'Bélgica',                    'Turkménistan',
                              '火鸡',                           'Jemen']
Length: 178, dtype: str

In [435]:
# cek semua country unik
sorted(df["country"].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Bélgica',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Estonie',
 'Ethiopia',
 'Fiji Islands',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Inde',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jemen',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Komoren',
 'Kosovo',
 'Kuwait',
 'Kyrghyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Letonia',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Malásia',
 'Marrocos',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Mexique',
 'Micronesia',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Polônia',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Saint-Vincent-et-les-Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Saudi Arabien',
 'Senegal',
 'Serbia',
 'Seychelles Islands',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Südkorea',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turkménistan',
 'Tuvalu',
 'USA United States of America',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'Гватемала',
 'Польша',
 'Турция',
 'كولومبيا',
 '火鸡']

In [436]:
country_fix = {

    "Polônia": "Poland",
    "Marrocos": "Morocco",
    "Турция": "Turkey",
    "火鸡": "Turkey",
    "Saudi Arabien": "Saudi Arabia",
    "Südkorea": "South Korea",
    "Bélgica": "Belgium",
    "Turkménistan": "Turkmenistan",
    "Jemen": "Yemen"

}

df["country"] = df["country"].replace(country_fix)

In [437]:
df["country"] = df["country"].replace(country_fix)

In [438]:
df["continent"] = df["country"].map(continent_map)

In [439]:
df["continent"].value_counts()

continent
Asia             4482
Europe           3357
Africa           1869
South America    1114
North America    1108
Oceania           748
Name: count, dtype: int64

In [440]:
df[df["continent"] == "Unknown"]["country"].unique()

<ArrowStringArray>
[]
Length: 0, dtype: str

In [441]:
sorted(df["country"].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Estonie',
 'Ethiopia',
 'Fiji Islands',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Inde',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Komoren',
 'Kosovo',
 'Kuwait',
 'Kyrghyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Letonia',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Malásia',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Mexique',
 'Micronesia',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Saint-Vincent-et-les-Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles Islands',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'USA United States of America',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'Гватемала',
 'Польша',
 'كولومبيا']

In [442]:
country_fix = {

    "Гватемала": "Guatemala",
    "Польша": "Poland",
    "كولومبيا": "Colombia"

}

In [443]:
df["country"] = df["country"].replace(country_fix)

In [444]:
sorted(df["country"].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Estonie',
 'Ethiopia',
 'Fiji Islands',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Inde',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Komoren',
 'Kosovo',
 'Kuwait',
 'Kyrghyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Letonia',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Malásia',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Mexique',
 'Micronesia',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Saint-Vincent-et-les-Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles Islands',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'USA United States of America',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [445]:
df["continent"] = df["country"].map(continent_map)

In [446]:
df["continent"].value_counts()

continent
Asia             4482
Europe           3357
Africa           1869
South America    1115
North America    1108
Oceania           748
Name: count, dtype: int64

## CHECK NEGARA YANG BELUM PUNYA CONTINENT

In [447]:
df[df["continent"].isnull()]["country"].unique()

<ArrowStringArray>
[                        'Albania',                         'Algeria',
                         'Andorra',                          'Angola',
             'Antigua and Barbuda',                         'Armenia',
                         'Austria',                      'Azerbaijan',
                         'Bahamas',                         'Bahrain',
 ...
                           'Libya',                          'Kosovo',
                            'Togo',                         'Malásia',
                         'Komoren',                         'Estonie',
                            'Inde',                         'Letonia',
                         'Mexique', 'Saint-Vincent-et-les-Grenadines']
Length: 166, dtype: str

In [448]:
import pandas as pd

df = pd.read_csv("Global_Weather.csv")

df_clean = df.copy()

import pycountry_convert as pc
import pycountry

In [449]:
def get_continent(country_name):

    try:
        country_code = pycountry.countries.lookup(country_name).alpha_2

        continent_code = pc.country_alpha2_to_continent_code(country_code)

        continent_dict = {
            "AF": "Africa",
            "AS": "Asia",
            "EU": "Europe",
            "NA": "North America",
            "SA": "South America",
            "OC": "Oceania"
        }

        return continent_dict[continent_code]

    except:
        return "Unknown"

In [450]:
df["continent"] = df["country"].apply(get_continent)

In [451]:
df["continent"].value_counts()

continent
Africa           17544
Asia             17493
Europe           15699
North America     8508
Unknown           4881
South America     4451
Oceania           4104
Name: count, dtype: int64

### total dataset clean nya = 72674 dari 72680  jadi ada selisih yg mau dicheck

In [452]:
df[df["continent"] == "Unknown"]["country"].unique()

<ArrowStringArray>
[                     'Cape Verde',    'Democratic Republic of Congo',
                       'Swaziland',                    'Fiji Islands',
                    'Vatican City',                     'Kyrghyzstan',
                      'Micronesia',                          'Turkey',
                       'Macedonia',                          'Russia',
              'Seychelles Islands',                     'Timor-Leste',
    'USA United States of America',                          'Kosovo',
                         'Malásia',                         'Komoren',
                        'كولومبيا',                         'Estonie',
                       'Гватемала',                            'Inde',
                         'Letonia',                          'Польша',
                         'Mexique',                         'Polônia',
                        'Marrocos',                          'Турция',
 'Saint-Vincent-et-les-Grenadines',                   'Saudi Arabien',
                        'Südkorea',                         'Bélgica',
                    'Turkménistan',                              '火鸡',
                           'Jemen']
Length: 33, dtype: str

In [453]:
country_fix = {

    "Kyrghyzstan": "Kyrgyzstan",
    "Malásia": "Malaysia",
    "Inde": "India",
    "Mexique": "Mexico",
    "Estonie": "Estonia",
    "Letonia": "Latvia",
    "Komoren": "Comoros",

    "Fiji Islands": "Fiji",
    "Macedonia": "North Macedonia",
    "Cape Verde": "Cabo Verde",

    "USA United States of America": "United States",

    "Seychelles Islands": "Seychelles",

    "Saint-Vincent-et-les-Grenadines":
        "Saint Vincent and the Grenadines"

}

In [454]:
df["country"] = df["country"].replace(country_fix)

In [455]:
df["continent"] = df["country"].apply(get_continent)

In [456]:
df["continent"].value_counts()

continent
Africa           18292
Asia             17868
Europe           16071
North America     8513
Oceania           4478
South America     4451
Unknown           3007
Name: count, dtype: int64

In [457]:
df[df["continent"] == "Unknown"]["country"].unique()

<ArrowStringArray>
['Democratic Republic of Congo',                    'Swaziland',
                 'Vatican City',                   'Micronesia',
                       'Turkey',                       'Russia',
                  'Timor-Leste',                       'Kosovo',
                     'كولومبيا',                    'Гватемала',
                       'Польша',                      'Polônia',
                     'Marrocos',                       'Турция',
                'Saudi Arabien',                     'Südkorea',
                      'Bélgica',                 'Turkménistan',
                           '火鸡',                        'Jemen']
Length: 20, dtype: str

In [458]:
country_fix = {

    "Democratic Republic of Congo": "Congo",
    "Swaziland": "Eswatini",
    "Vatican City": "Vatican City State",
    "Micronesia": "Federated States of Micronesia",
    "Turkey": "Türkiye",
    "Russia": "Russian Federation",
    "Timor-Leste": "East Timor"

}

In [459]:
df.loc[df["country"] == "Kosovo", "continent"] = "Europe"

In [460]:
df["country"] = df["country"].replace(country_fix)

In [461]:
df["continent"] = df["country"].apply(get_continent)

In [462]:
df[df["continent"] == "Unknown"]["country"].unique()

<ArrowStringArray>
['Vatican City State',         'East Timor',             'Kosovo',
           'كولومبيا',          'Гватемала',             'Польша',
            'Polônia',           'Marrocos',             'Турция',
      'Saudi Arabien',           'Südkorea',            'Bélgica',
       'Turkménistan',                 '火鸡',              'Jemen']
Length: 15, dtype: str

In [463]:
df["continent"].value_counts()

continent
Africa           19035
Asia             18613
Europe           16458
North America     8513
Oceania           4851
South America     4451
Unknown            759
Name: count, dtype: int64

### Total dataset lengkap = 72.674. Namun masih ada 1% yaitu 747 data tidak mengenal negara ini ke continent.

In [464]:
print(df.shape)

(72680, 42)

In [465]:
print(df.columns.tolist())

['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'continent']

In [466]:
selected_columns = [
    "country",
    "location_name",
    "latitude",
    "longitude",

    "temperature_celsius",
    "humidity",
    "wind_kph",
    "pressure_mb",
    "uv_index",
    "cloud",
    "visibility_km",

    "air_quality_PM2.5",
    "air_quality_PM10",
    "air_quality_Ozone",
    "air_quality_Carbon_Monoxide",

    "condition_text"
]

df = df[selected_columns]

### Persiapan ke app.py dan 3 page

In [467]:
df = pd.read_csv("Global_Weather.csv")
df_clean = df.copy()
df_clean.to_csv("Global_Weather_Clean.csv", index=False)

#### double check jika benear data sudah bersih:

In [468]:
df = pd.read_csv("Global_Weather.csv")
df_clean = df.copy()
df_clean.to_csv("Global_Weather_Clean.csv", index=False)

In [469]:
df_clean.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [470]:
df_clean.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
from sklearn.ensemble import IsolationForest

# ====================================
# CHECK COLUMNS
# ====================================

print("COLUMNS:")
print(df_clean.columns.tolist())

# ====================================
# CREATE X
# ====================================

X = df_clean[
    [
        "temperature_celsius",
        "humidity",
        "wind_kph",
        "pressure_mb",
        "uv_index",
        "cloud",
        "visibility_km",
        "air_quality_PM2.5",
        "air_quality_PM10"
    ]
]

print("\nX created successfully!")

# ====================================
# CREATE MODEL
# ====================================

model = IsolationForest(
    contamination=0.02,
    random_state=42
)

print("\nModel created!")

# ====================================
# FIT MODEL
# ====================================

model.fit(X)

print("\nModel fitted!")

# ====================================
# CREATE PREDICTIONS
# ====================================

predictions = model.predict(X)

print("\nPredictions created!")

print(predictions[:10])

# ====================================
# SAVE TO DATAFRAME
# ====================================

df_clean["anomaly"] = predictions

print("\nAnomaly column added!")

# ====================================
# FINAL CHECK
# ====================================

print(df_clean.columns.tolist())

print("\nAnomaly counts:")
print(df_clean["anomaly"].value_counts())

COLUMNS:
['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination']

X created successfully!

Model created!

Model fitted!

Predictions created!
[1 1 1 1 1 1 1 1 1 1]

Anomaly column added!
['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'anomaly']

Anomaly counts:
anomaly
 1    71226
-1     1454
Name: count, dtype: int64

In [ ]:
df_clean[
    df_clean["anomaly"] == -1
].head(10)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,anomaly
35,Chile,Santiago,-33.45,-70.67,America/Santiago,1715849100,2024-05-16 04:45,1.0,33.8,Clear,...,268.6,5,10,07:28 AM,05:50 PM,02:23 PM,12:56 AM,Waxing Gibbous,55,-1
78,Indonesia,Jakarta,-6.21,106.85,Asia/Jakarta,1715849100,2024-05-16 15:45,32.0,89.6,Partly cloudy,...,224.0,5,10,05:54 AM,05:44 PM,12:50 PM,12:15 AM,Waxing Gibbous,55,-1
230,Chile,Santiago,-33.45,-70.67,America/Santiago,1715868000,2024-05-16 10:00,2.0,35.6,Sunny,...,873.4,6,10,07:28 AM,05:50 PM,02:23 PM,12:56 AM,Waxing Gibbous,55,-1
273,Indonesia,Jakarta,-6.21,106.85,Asia/Jakarta,1715868000,2024-05-16 21:00,29.0,84.2,Mist,...,621.5,6,10,05:54 AM,05:44 PM,12:50 PM,12:15 AM,Waxing Gibbous,55,-1
468,Indonesia,Jakarta,-6.21,106.85,Asia/Jakarta,1715961600,2024-05-17 23:00,28.0,82.4,Mist,...,1002.2,6,10,05:54 AM,05:44 PM,01:28 PM,12:59 AM,Waxing Gibbous,64,-1
617,Chile,Santiago,-33.45,-70.67,America/Santiago,1716042600,2024-05-18 10:30,5.0,41.0,Mist,...,682.1,6,10,07:30 AM,05:49 PM,03:11 PM,02:46 AM,Waxing Gibbous,73,-1
660,Indonesia,Jakarta,-6.21,106.85,Asia/Jakarta,1716042600,2024-05-18 21:30,28.0,82.4,Partly cloudy,...,376.6,6,10,05:55 AM,05:44 PM,02:05 PM,01:41 AM,Waxing Gibbous,73,-1
707,Niger,Niamey,13.52,2.12,Africa/Niamey,1716042600,2024-05-18 15:30,43.0,109.4,Overcast,...,262.3,3,7,06:24 AM,07:12 PM,03:14 PM,02:57 AM,Waxing Gibbous,73,-1
811,Chile,Santiago,-33.45,-70.67,America/Santiago,1716127200,2024-05-19 10:00,3.0,37.4,Mist,...,544.4,6,10,07:31 AM,05:48 PM,03:35 PM,03:42 AM,Waxing Gibbous,81,-1
1006,Chile,Santiago,-33.45,-70.67,America/Santiago,1716215400,2024-05-20 10:30,10.0,50.0,Mist,...,565.7,6,10,07:31 AM,05:48 PM,04:00 PM,04:37 AM,Waxing Gibbous,88,-1

### Dataset checking

In [478]:
# ====================================
# FINAL DATASET CHECK
# ====================================

print("\n📦 Final dataset shape:")
print(df_clean.shape)

print("\n📋 Final columns:")
print(df_clean.columns.tolist())

print("\n🔍 Duplicate check:")
print(df_clean.duplicated().sum())

print("\n🔍 Missing values check:")
print(df_clean.isnull().sum())

print("\n📊 Dataset description:")
print(df_clean.describe())

print("\n🚨 Sample anomalies:")
print(

    df_clean[
        df_clean["anomaly"] == -1
    ].head()
)

📦 Final dataset shape:
(72680, 42)

📋 Final columns:
['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'anomaly']

🔍 Duplicate check:
0

🔍 Missing values check:
country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
anomaly                         0
dtype: int64

📊 Dataset description:
           latitude     longitude  last_updated_epoch  temperature_celsius  \
count  72680.000000  72680.000000        7.268000e+04         72680.000000
mean      19.131726     22.192388        1.732041e+09            22.178485
std       24.473876     65.817916        9.365241e+06             9.389486
min      -41.300000   -175.200000        1.715849e+09           -24.900000
25%        3.750000     -6.836100        1.723982e+09            16.800000
50%       17.250000     23.316700        1.732092e+09            24.500000
75%       40.400000     50.580000        1.740132e+09            28.300000
max       64.150000    179.220000        1.748162e+09            49.200000

       temperature_fahrenheit      wind_mph      wind_kph   wind_degree  \
count            72680.000000  72680.000000  72680.000000  72680.000000
mean                71.922887      8.278520     13.326626    168.654554
std                 16.900842      8.651946     13.921876    103.626180
min                -12.800000      2.200000      3.600000      1.000000
25%                 62.200000      4.000000      6.500000     80.000000
50%                 76.100000      6.900000     11.200000    160.000000
75%                 82.900000     11.400000     18.400000    256.000000
max                120.600000   1841.200000   2963.200000    360.000000

        pressure_mb   pressure_in  ...  air_quality_Carbon_Monoxide  \
count  72680.000000  72680.000000  ...                 72680.000000
mean    1014.064241     29.944688  ...                   524.755661
std       12.561074      0.370895  ...                   896.920503
min      947.000000     27.960000  ...                 -9999.000000
25%     1010.000000     29.830000  ...                   233.100000
50%     1013.000000     29.920000  ...                   329.300000
75%     1017.000000     30.040000  ...                   510.600000
max     3006.000000     88.770000  ...                 38879.398000

       air_quality_Ozone  air_quality_Nitrogen_dioxide  \
count       72680.000000                  72680.000000
mean           63.959137                     15.354301
std            34.672720                     26.142281
min             0.000000                      0.000000
25%            41.000000                      1.110000
50%            61.000000                      3.885000
75%            82.000000                     17.020000
max           480.700000                    427.700000

       air_quality_Sulphur_dioxide  air_quality_PM2.5  air_quality_PM10  \
count                 72680.000000       72680.000000      72680.000000
mean                     11.389241          26.072034         54.066043
std                      45.230503          43.078374        166.945878
min                   -9999.000000           0.168000      -1848.150000
25%                       0.800000           6.400000          9.620000
50%                       2.405000          14.430000         21.645000
75%                       9.100000          30.525000         46.805000
max                     521.330000        1614.100000       6037.290000

       air_quality_us-epa-index  air_quality_gb-defra-index  \
count              72680.000000                72680.000000
mean                   1.752422                    2.764062
std                    0.994329                    2.610547
min                    1.000000                    1.000000
25%                    1.000000                    1.000000
50%                    1.000000                    2.000000
75%                    2.000000                    3.000000
max                    6.000000                   10.000000

       moon_illumination       anomaly
count       72680.000000  72680.000000
mean           50.335856      0.959989
std            34.972720      0.280040
min             0.000000     -1.000000
25%            16.000000      1.000000
50%            51.000000      1.000000
75%            85.000000      1.000000
max           100.000000      1.000000

[8 rows x 31 columns]

🚨 Sample anomalies:
       country location_name  latitude  longitude          timezone  \
35       Chile      Santiago    -33.45     -70.67  America/Santiago
78   Indonesia       Jakarta     -6.21     106.85      Asia/Jakarta
230      Chile      Santiago    -33.45     -70.67  America/Santiago
273  Indonesia       Jakarta     -6.21     106.85      Asia/Jakarta
468  Indonesia       Jakarta     -6.21     106.85      Asia/Jakarta

     last_updated_epoch      last_updated  temperature_celsius  \
35           1715849100  2024-05-16 04:45                  1.0
78           1715849100  2024-05-16 15:45                 32.0
230          1715868000  2024-05-16 10:00                  2.0
273          1715868000  2024-05-16 21:00                 29.0
468          1715961600  2024-05-17 23:00                 28.0

     temperature_fahrenheit condition_text  ...  air_quality_PM10  \
35                     33.8          Clear  ...             268.6
78                     89.6  Partly cloudy  ...             224.0
230                    35.6          Sunny  ...             873.4
273                    84.2           Mist  ...             621.5
468                    82.4           Mist  ...            1002.2

     air_quality_us-epa-index  air_quality_gb-defra-index   sunrise    sunset  \
35                          5                          10  07:28 AM  05:50 PM
78                          5                          10  05:54 AM  05:44 PM
230                         6                          10  07:28 AM  05:50 PM
273                         6                          10  05:54 AM  05:44 PM
468                         6                          10  05:54 AM  05:44 PM

     moonrise   moonset      moon_phase  moon_illumination  anomaly
35   02:23 PM  12:56 AM  Waxing Gibbous                 55       -1
78   12:50 PM  12:15 AM  Waxing Gibbous                 55       -1
230  02:23 PM  12:56 AM  Waxing Gibbous                 55       -1
273  12:50 PM  12:15 AM  Waxing Gibbous                 55       -1
468  01:28 PM  12:59 AM  Waxing Gibbous                 64       -1

[5 rows x 42 columns]

In [ ]:
print(df_clean.columns.tolist())

['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'anomaly']

### Penambahan continent

In [479]:
import pycountry_convert as pc

# ====================================
# FIX COUNTRY NAMES
# ====================================

country_fix = {

    "Kyrghyzstan": "Kyrgyzstan",
    "Malásia": "Malaysia",
    "Inde": "India",
    "Mexique": "Mexico",
    "Estonie": "Estonia",
    "Letonia": "Latvia",
    "Komoren": "Comoros",

    "Fiji Islands": "Fiji",
    "Macedonia": "North Macedonia",
    "Cape Verde": "Cabo Verde",

    "USA United States of America":
        "United States",

    "Seychelles Islands":
        "Seychelles",

    "Saint-Vincent-et-les-Grenadines":
        "Saint Vincent and the Grenadines",

    "Democratic Republic of Congo":
        "Congo",

    "Swaziland":
        "Eswatini",

    "Vatican City":
        "Vatican City State",

    "Micronesia":
        "Federated States of Micronesia",

    "Turkey":
        "Türkiye",

    "Russia":
        "Russian Federation",

    "Timor-Leste":
        "East Timor"
}

# ====================================
# APPLY COUNTRY FIX
# ====================================

df_clean["country"] = (
    df_clean["country"]
    .replace(country_fix)
)

# ====================================
# FUNCTION
# ====================================

def get_continent(country_name):

    try:

        country_code = (
            pc.country_name_to_country_alpha2(
                country_name
            )
        )

        continent_code = (
            pc.country_alpha2_to_continent_code(
                country_code
            )
        )

        continent_map = {

            "AF": "Africa",
            "AS": "Asia",
            "EU": "Europe",
            "NA": "North America",
            "SA": "South America",
            "OC": "Oceania"
        }

        return continent_map.get(
            continent_code,
            "Unknown"
        )

    except:
        return "Unknown"

# ====================================
# CREATE CONTINENT COLUMN
# ====================================

df_clean["continent"] = (
    df_clean["country"]
    .apply(get_continent)
)

# ====================================
# CHECK RESULT
# ====================================

print(df_clean["continent"].value_counts())

print("\nFinal Columns:")
print(df_clean.columns.tolist())

continent
Africa           19035
Asia             18613
Europe           16458
North America     8513
Oceania           4851
South America     4451
Unknown            759
Name: count, dtype: int64

Final Columns:
['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'anomaly', 'continent']

In [480]:
df_clean.to_csv(
    "Global_Weather_Clean.csv",
    index=False
)

In [486]:
# ====================================
# FINAL DATASET CHECKING
# ====================================

print("📦 Final dataset shape:")
print(df_clean.shape)

print("\n")

# ====================================
# FINAL COLUMNS
# ====================================

print("📋 Final columns:")
print(df_clean.columns.tolist())

print("\n")

# ====================================
# DUPLICATE CHECK
# ====================================

print("🔍 Duplicate check:")
print(df_clean.duplicated().sum())

print("\n")

# ====================================
# MISSING VALUES CHECK
# ====================================

print("🔍 Missing values check:")
print(df_clean.isnull().sum())

print("\n")

# ====================================
# CONTINENT CHECK
# ====================================

print("🌍 Continent distribution:")
print(df_clean["continent"].value_counts())

print("\n")

# ====================================
# ANOMALY CHECK
# ====================================

print("🚨 Anomaly distribution:")
print(df_clean["anomaly"].value_counts())

print("\n")

# ====================================
# UNKNOWN COUNTRIES
# ====================================

unknown_countries = (

    df_clean[
        df_clean["continent"] == "Unknown"
    ]["country"]
    .unique()
)

print("❓ Unknown countries:")
print(sorted(unknown_countries))

print("\n")

# ====================================
# INVALID VALUES CHECK
# ====================================

print("🌪 Invalid wind > 200:")
print(
    (df_clean["wind_kph"] > 200).sum()
)

print("\n")

print("☁ Invalid PM2.5 < 0:")
print(
    (df_clean["air_quality_PM2.5"] < 0).sum()
)

print("\n")

# ====================================
# SAMPLE ANOMALIES
# ====================================

print("🚨 Sample anomalies:")

print(
    df_clean[
        df_clean["anomaly"] == -1
    ].head()
)

check_dates.py

📦 Final dataset shape:
(72680, 43)


📋 Final columns:
['country', 'location_name', 'latitude', 'longitude', 'timezone', 'last_updated_epoch', 'last_updated', 'temperature_celsius', 'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph', 'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in', 'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius', 'feels_like_fahrenheit', 'visibility_km', 'visibility_miles', 'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone', 'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'anomaly', 'continent']


🔍 Duplicate check:
0


🔍 Missing values check:
country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
anomaly                         0
continent                       0
dtype: int64


🌍 Continent distribution:
continent
Africa           19035
Asia             18613
Europe           16458
North America     8513
Oceania           4851
South America     4451
Unknown            759
Name: count, dtype: int64


🚨 Anomaly distribution:
anomaly
 1    71226
-1     1454
Name: count, dtype: int64


❓ Unknown countries:
['Bélgica', 'East Timor', 'Jemen', 'Kosovo', 'Marrocos', 'Polônia', 'Saudi Arabien', 'Südkorea', 'Turkménistan', 'Vatican City State', 'Гватемала', 'Польша', 'Турция', 'كولومبيا', '火鸡']


🌪 Invalid wind > 200:
4


☁ Invalid PM2.5 < 0:
0


🚨 Sample anomalies:
       country location_name  latitude  longitude          timezone  \
35       Chile      Santiago    -33.45     -70.67  America/Santiago
78   Indonesia       Jakarta     -6.21     106.85      Asia/Jakarta
230      Chile      Santiago    -33.45     -70.67  America/Santiago
273  Indonesia       Jakarta     -6.21     106.85      Asia/Jakarta
468  Indonesia       Jakarta     -6.21     106.85      Asia/Jakarta

     last_updated_epoch      last_updated  temperature_celsius  \
35           1715849100  2024-05-16 04:45                  1.0
78           1715849100  2024-05-16 15:45                 32.0
230          1715868000  2024-05-16 10:00                  2.0
273          1715868000  2024-05-16 21:00                 29.0
468          1715961600  2024-05-17 23:00                 28.0

     temperature_fahrenheit condition_text  ...  air_quality_us-epa-index  \
35                     33.8          Clear  ...                         5
78                     89.6  Partly cloudy  ...                         5
230                    35.6          Sunny  ...                         6
273                    84.2           Mist  ...                         6
468                    82.4           Mist  ...                         6

     air_quality_gb-defra-index   sunrise    sunset  moonrise   moonset  \
35                           10  07:28 AM  05:50 PM  02:23 PM  12:56 AM
78                           10  05:54 AM  05:44 PM  12:50 PM  12:15 AM
230                          10  07:28 AM  05:50 PM  02:23 PM  12:56 AM
273                          10  05:54 AM  05:44 PM  12:50 PM  12:15 AM
468                          10  05:54 AM  05:44 PM  01:28 PM  12:59 AM

         moon_phase  moon_illumination  anomaly      continent
35   Waxing Gibbous                 55       -1  South America
78   Waxing Gibbous                 55       -1           Asia
230  Waxing Gibbous                 55       -1  South America
273  Waxing Gibbous                 55       -1           Asia
468  Waxing Gibbous                 64       -1           Asia

[5 rows x 43 columns]

NameError: name 'check_dates' is not defined

In [482]:
df_clean.to_csv(
    "Global_Weather_Clean.csv",
    index=False
)

In [485]:
df["last_updated"] = pd.to_datetime(
    df["last_updated"]
)

print(df["last_updated"].min())
print(df["last_updated"].max())
print(df["last_updated"].dt.year.value_counts())

2024-05-16 01:45:00
2025-05-25 21:30:00
last_updated
2024    44469
2025    28211
Name: count, dtype: int64

In [487]:
import pandas as pd

df = pd.read_csv("Global_Weather_Clean.csv")

# Convert ke datetime
df["last_updated"] = pd.to_datetime(
    df["last_updated"],
    errors="coerce"
)

print("=" * 50)
print("MIN DATE")
print(df["last_updated"].min())

print("=" * 50)
print("MAX DATE")
print(df["last_updated"].max())

print("=" * 50)
print("TOTAL RECORDS")
print(len(df))

==================================================
MIN DATE
2024-05-16 01:45:00
==================================================
MAX DATE
2025-05-25 21:30:00
==================================================
TOTAL RECORDS
72680

In [488]:
df["year"] = df["last_updated"].dt.year

print(
    df["year"]
    .value_counts()
    .sort_index()
)

year
2024    44469
2025    28211
Name: count, dtype: int64

In [489]:
df["month"] = df["last_updated"].dt.month

monthly_count = (
    df.groupby(
        ["year", "month"]
    )
    .size()
    .reset_index(name="records")
)

print(monthly_count)

    year  month  records
0   2024      5     3298
1   2024      6     5807
2   2024      7     5581
3   2024      8     6045
4   2024      9     5856
5   2024     10     6020
6   2024     11     5817
7   2024     12     6045
8   2025      1     6006
9   2025      2     5457
10  2025      3     6041
11  2025      4     5850
12  2025      5     4857

In [490]:
unique_months = (
    df["last_updated"]
    .dt.to_period("M")
    .nunique()
)

print(
    "Unique Months:",
    unique_months
)

Unique Months: 13

In [491]:
df["year"] = (
    df["last_updated"]
    .dt.year
)

df["month"] = (
    df["last_updated"]
    .dt.month
)

df["month_name"] = (
    df["last_updated"]
    .dt.strftime("%B")
)

df["year_month"] = (
    df["last_updated"]
    .dt.strftime("%Y-%m")
)

In [492]:
print(
    df["moon_phase"]
    .value_counts()
)

moon_phase
Waxing Gibbous     16065
Waning Crescent    15807
Waning Gibbous     15546
Waxing Crescent    15179
Full Moon           2635
Last Quarter        2628
New Moon            2460
First Quarter       2360
Name: count, dtype: int64

In [493]:
print(
    df["moon_illumination"]
    .describe()
)

count    72680.000000
mean        50.335856
std         34.972720
min          0.000000
25%         16.000000
50%         51.000000
75%         85.000000
max        100.000000
Name: moon_illumination, dtype: float64

In [494]:
print(
    df["visibility_km"]
    .describe()
)

count    72680.000000
mean         9.614337
std          2.532462
min          0.000000
25%         10.000000
50%         10.000000
75%         10.000000
max         32.000000
Name: visibility_km, dtype: float64

In [495]:
print(df["cloud"].describe())

print(df["wind_kph"].describe())

count    72680.000000
mean        39.892102
std         33.854933
min          0.000000
25%          2.000000
50%         31.000000
75%         75.000000
max        100.000000
Name: cloud, dtype: float64
count    72680.000000
mean        13.326626
std         13.921876
min          3.600000
25%          6.500000
50%         11.200000
75%         18.400000
max       2963.200000
Name: wind_kph, dtype: float64

In [496]:
df["wind_kph"].sort_values(ascending=False).head(20)

7601     2963.2
7248      272.2
1193      258.8
8675      205.9
834       172.1
51526      91.1
9129       81.0
19892      78.1
35380      76.7
22816      76.0
43180      76.0
48797      70.2
8464       69.8
12610      69.1
47658      68.0
56593      67.3
67946      66.2
33820      66.2
12897      65.2
3829       65.2
Name: wind_kph, dtype: float64

In [497]:
Q1 = df["wind_kph"].quantile(0.25)
Q3 = df["wind_kph"].quantile(0.75)

IQR = Q3 - Q1

upper_bound = Q3 + (1.5 * IQR)

print("Q1:", Q1)
print("Q3:", Q3)
print("Upper Bound:", upper_bound)

Q1: 6.5
Q3: 18.4
Upper Bound: 36.25

In [498]:
df["wind_kph"].quantile(0.99)

df["wind_kph"].quantile(0.995)

wind_cap = df["wind_kph"].quantile(0.995)

df["wind_kph_clean"] = (
    df["wind_kph"]
    .clip(upper=wind_cap)
)

In [499]:
print(df["uv_index"].describe())

print(df["humidity"].describe())

print(df["air_quality_PM2.5"].describe())

count    72680.000000
mean         3.983459
std          3.627636
min          0.000000
25%          0.700000
50%          3.300000
75%          7.000000
max         16.300000
Name: uv_index, dtype: float64
count    72680.000000
mean        63.637369
std         24.317889
min          2.000000
25%         46.000000
50%         69.000000
75%         83.000000
max        100.000000
Name: humidity, dtype: float64
count    72680.000000
mean        26.072034
std         43.078374
min          0.168000
25%          6.400000
50%         14.430000
75%         30.525000
max       1614.100000
Name: air_quality_PM2.5, dtype: float64

In [500]:
df["pm25_clean"] = df["air_quality_PM2.5"].clip(0, 200)
df["wind_clean"] = df["wind_kph"].clip(0, 80)

In [501]:
df["wind_kph"] = df["wind_kph"].clip(0, 80)
df["air_quality_PM2.5"] = df["air_quality_PM2.5"].clip(0, 200)